#import <Foundation/Foundation.h>

//CLIENT
FOUNDATION_EXPORT NSString *const SDK_VERSION;
FOUNDATION_EXPORT NSString *const iOMNIATA;

//HTTP CONTENT KEY_VAL PARAMS
FOUNDATION_EXPORT NSString *const EVENT_POST_KEY_TYPE;
FOUNDATION_EXPORT NSString *const EVENT_POST_KEY_TOTAL;
FOUNDATION_EXPORT NSString *const EVENT_POST_VAL_TYPE_LOAD;
FOUNDATION_EXPORT NSString *const EVENT_POST_VAL_TYPE_REVENUE;
FOUNDATION_EXPORT NSString *const EVENT_POST_VAL_DEFAULT_CURRENCY;
FOUNDATION_EXPORT NSString *const EVENT_POST_KEY_REF_CODE;
FOUNDATION_EXPORT NSString *const EVENT_POST_KEY_REF_UID;
FOUNDATION_EXPORT NSString *const EVENT_POST_KEY_REF_APP_KEY;
FOUNDATION_EXPORT NSString *const EVENT_POST_KEY_TIME;
FOUNDATION_EXPORT NSString* const EVENT_POST_KEY_EVENT;
FOUNDATION_EXPORT NSString* const EVENT_POST_KEY_USER_PARAMS;
FOUNDATION_EXPORT NSString* const EVENT_POST_KEY_API_KEY;
FOUNDATION_EXPORT NSString* const EVENT_POST_KEY_USER_ID;
FOUNDATION_EXPORT NSString* const EVENT_POST_KEY_CHANNEL_ID;
FOUNDATION_EXPORT NSString* const EVENT_POST_KEY_USER_AGENT_MODEL;
FOUNDATION_EXPORT NSString* const EVENT_POST_KEY_USER_AGENT_OS;
FOUNDATION_EXPORT NSString* const EVENT_POST_KEY_CLIENT_VERSION;

FOUNDATION_EXPORT NSString *const EVENT_LOG_FILE_NAME;
FOUNDATION_EXPORT NSString *const EVENT_LOG_FILE_DIR;

FOUNDATION_EXPORT NSUInteger const EVENT_PROCESSOR_THREAD_DELAY;
FOUNDATION_EXPORT NSUInteger const EVENT_PERSIST_THREAD_DELAY;

FOUNDATION_EXPORT NSUInteger const INTERNAL_SERVER_ERROR;
FOUNDATION_EXPORT NSUInteger const HTTP_OK;
FOUNDATION_EXPORT NSUInteger const HTTP_BAD_REQUEST;
FOUNDATION_EXPORT NSUInteger const SLEEP_TIME;
FOUNDATION_EXPORT NSUInteger const MAX_SLEEP;
FOUNDATION_EXPORT NSString *const ERROR;

//SERVER
FOUNDATION_EXPORT NSString *const ROOT_URL;
FOUNDATION_EXPORT NSString *const TEST_URL;

FOUNDATION_EXPORT NSString *const EVENTS_TRACK_SUB_URL;
FOUNDATION_EXPORT NSString *const CONFIG_SUB_URL;
FOUNDATION_EXPORT NSString *const CHANNEL_MSGS_SUB_URL;

FOUNDATION_EXPORT NSString *const CONFIG_JSON_MAX_TRACK_RETRIES;
FOUNDATION_EXPORT NSString *const CONFIG_JSON_MAX_CHANNEL_RETRIES;
FOUNDATION_EXPORT NSString *const CONFIG_JSON_MAX_BATCH_SIZE;
FOUNDATION_EXPORT NSString *const CONFIG_JSON_BATCH_DELAY;
FOUNDATION_EXPORT NSString *const CONFIG_JSON_MIN_RETRY_DELAY;

FOUNDATION_EXPORT NSString *const CHANNEL_DATA_JSON_CONTENT;

FOUNDATION_EXPORT BOOL const LOAD_CONFIG_INTERNAL;

typedef enum {
    SMT_SERVER_CONFIG = 0,
    SMT_SERVER_TRACK,
    SMT_SERVER_CHANNEL
} SMT_SERVERS;